image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://192.168.112.3:2375"
  DOCKER_REGISTRY: 192.168.112.3:5000 
  DOCKER_IMAGE: $DOCKER_REGISTRY/myapp:$CI_COMMIT_SHA
  KUBECONFIG: "/home/osboxes/.kube/config"
  CA: "/home/osboxes/.minikube/ca.crt"
  CLIENTCRT: "/home/osboxes/.minikube/profiles/minikube/client.crt"
  CLIENTKEY: "/home/osboxes/.minikube/profiles/minikube/client.key"
  KUBE_NAMESPACE: "default"
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

before_script:
  - chmod +x node_modules/.bin/mocha

build_job:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

test_job:
  stage: test
  script:
    - docker run --rm $DOCKER_IMAGE npm test 

# deploy_to_Docker:
#   stage: deploy
#
#   script:
#     - docker pull $DOCKER_IMAGE
#     - docker run -d -p 3000:3000 $DOCKER_IMAGE
deploy_to_minikube:
  image: buildpack-deps:bullseye-curl  
  stage: deploy
  variables:
    KUBECONFIG: "/home/osboxes/.kube/config"
    CA: "/home/osboxes/.minikube/ca.crt"
    CLIENTCRT: "/home/osboxes/.minikube/profiles/minikube/client.crt"
    CLIENTKEY: "/home/osboxes/.minikube/profiles/minikube/client.key"
    KUBE_NAMESPACE: "default"
  script:
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p /root/.kube
    - cp  $KUBECONFIG /root/.kube/config
    - cp  $CA /root/.kube/config
    - cp  $CLIENTCRT /root/.kube/config 
    - cp  $CLIENTKEY /root/.kube/config
    - kubectl config set-cluster minikube --server=https://192.168.49.2:8443 --certificate-authority=$CA
    - kubectl config set-credentials minikube --client-certificate=$CLIENTCRT --client-key=$CLIENTCRT
    - kubectl config set-context minikube --cluster=minikube --namespace=$KUBE_NAMESPACE --user=minikube
    - kubectl config use-context minikube
    - kubectl get nodes
    - kubectl apply -f kube_manifests/deployment.yaml
    - kubectl apply -f kube_manifests/service.yaml
    
 